name: Scorecard

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  id-token: none        # ⚠ global id-token doit être NONE
  contents: read        # minimum nécessaire

jobs:
  run-scorecard:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # seulement pour ce job
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Run Scorecard
        uses: ossf/scorecard-action@v5
        with:
          output: results.json
          show-details: true
      - name: Upload Scorecard results
        uses: actions/upload-artifact@v3
        with:
          name: scorecard-results
          path: results.json