name: OpenSSF Scorecard Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # chaque semaine (facultatif)

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.4.3
        with:
          path: .                      # chemin vers ton repo
          results_format: sarif         # ou json, csv
          results_path: scorecard.sarif  # chemin du fichier de sortie